const InstructionsRegistry = [
  {
    name: 'cd-module',
    flag: 'cd-module',
    label: 'cd-module',
    description: 'Create a developer cd-module environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 3,
      cdObjTypeName: 'cd-module',
      cdObjTypeGuid: '8b4cf8de-1ffc-4575-9e73-4ccf45a7756b',
      modCraftController: 'CdModule',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'CdModule',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'model',
    flag: 'model',
    label: 'model',
    description: 'Create a developer model environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 5,
      cdObjTypeName: 'model',
      cdObjTypeGuid: 'f028f009-1a2d-40d4-b284-645c855ad04c',
      modCraftController: 'CdModel',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'CdModel',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'controller',
    flag: 'controller',
    label: 'controller',
    description: 'Create a developer controller environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 6,
      cdObjTypeName: 'controller',
      cdObjTypeGuid: 'cbbd698d-34a9-4982-a75a-cfe7797c1d00',
      modCraftController: 'CdController',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'CdController',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'action',
    flag: 'action',
    label: 'action',
    description: 'Create a developer action environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 8,
      cdObjTypeName: 'action',
      cdObjTypeGuid: '55ffe474-f46b-452b-9a13-01c258995cdb',
      modCraftController: 'CdAction',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'CdAction',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'cd-app',
    flag: 'cd-app',
    label: 'cd-app',
    description: 'Create a developer cd-app environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 33,
      cdObjTypeName: 'cd-app',
      cdObjTypeGuid: 'd6507c5d-a7ca-41fb-ad5f-dc5ceba46489',
      modCraftController: 'CdApp',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'CdApp',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'package',
    flag: 'package',
    label: 'package',
    description: 'Create a developer package environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 34,
      cdObjTypeName: 'package',
      cdObjTypeGuid: 'cb35a1da-51b5-41a6-a147-4798de7b3b38',
      modCraftController: 'Package',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Package',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'test-bed',
    flag: 'test-bed',
    label: 'test-bed',
    description: 'Create a developer test-bed environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 126,
      cdObjTypeName: 'test-bed',
      cdObjTypeGuid: '8bf59db2-a2c2-4da0-ad28-bce77c022ce5',
      modCraftController: 'TestBed',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'TestBed',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'production',
    flag: 'production',
    label: 'production',
    description: 'Create a developer production environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 127,
      cdObjTypeName: 'production',
      cdObjTypeGuid: '010ef125-937a-4e7a-b571-2be23976946d',
      modCraftController: 'Production',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Production',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'package',
    flag: 'package',
    label: 'package',
    description: 'Create a developer package environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 128,
      cdObjTypeName: 'package',
      cdObjTypeGuid: '54b178d5-fc96-4aaf-97c7-c37a9c8c3f84',
      modCraftController: 'Package',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Package',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'sandbox',
    flag: 'sandbox',
    label: 'sandbox',
    description: 'Create a developer sandbox environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 129,
      cdObjTypeName: 'sandbox',
      cdObjTypeGuid: 'aa943c76-1998-4165-ab75-4424c9755587',
      modCraftController: 'Sandbox',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Sandbox',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'method',
    flag: 'method',
    label: 'method',
    description: 'Create a developer method environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 130,
      cdObjTypeName: 'method',
      cdObjTypeGuid: '647e5383-e9bc-447c-944c-39b892670711',
      modCraftController: 'CdMethod',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'CdMethod',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'dev-roadmap',
    flag: 'dev-roadmap',
    label: 'dev-roadmap',
    description: 'Create a developer dev-roadmap environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 131,
      cdObjTypeName: 'dev-roadmap',
      cdObjTypeGuid: '2c132caa-bde3-404f-884c-e6abe6257b1d',
      modCraftController: 'DevRoadmap',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'DevRoadmap',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'dev-doc',
    flag: 'dev-doc',
    label: 'dev-doc',
    description: 'Create a developer dev-doc environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 132,
      cdObjTypeName: 'dev-doc',
      cdObjTypeGuid: 'f8705dbb-814b-4649-8a44-f9d43d1fdba4',
      modCraftController: 'DevDoc',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'DevDoc',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'dev-changelog',
    flag: 'dev-changelog',
    label: 'dev-changelog',
    description: 'Create a developer dev-changelog environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 133,
      cdObjTypeName: 'dev-changelog',
      cdObjTypeGuid: 'f38a4627-32e9-44fc-9b22-dbab38d2735b',
      modCraftController: 'DevChangelog',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'DevChangelog',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'cd-api',
    flag: 'cd-api',
    label: 'cd-api',
    description: 'Create a developer cd-api environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 134,
      cdObjTypeName: 'cd-api',
      cdObjTypeGuid: 'c3279848-312d-42fa-91f0-0be2e27052d1',
      modCraftController: 'CdApi',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'CdApi',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'frontend',
    flag: 'frontend',
    label: 'frontend',
    description: 'Create a developer frontend environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 200,
      cdObjTypeName: 'frontend',
      cdObjTypeGuid: '23efab2b-1f61-40f5-a84d-6f9978b57e57',
      modCraftController: 'Frontend',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Frontend',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'api',
    flag: 'api',
    label: 'api',
    description: 'Create a developer api environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 201,
      cdObjTypeName: 'api',
      cdObjTypeGuid: 'c9677cd1-4e4e-46fd-958c-e60f59f82bd1',
      modCraftController: 'Api',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Api',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'cd-module',
    flag: 'cd-module',
    label: 'cd-module',
    description: 'Create a developer cd-module environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 203,
      cdObjTypeName: 'cd-module',
      cdObjTypeGuid: 'f6bc1cf9-bdef-4ad1-837e-1e0ce29eb104',
      modCraftController: 'CdModule',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'CdModule',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'push-server',
    flag: 'push-server',
    label: 'push-server',
    description: 'Create a developer push-server environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 204,
      cdObjTypeName: 'push-server',
      cdObjTypeGuid: '4d1d69de-06f2-41f6-b4f4-6db16091f6f1',
      modCraftController: 'PushServer',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'PushServer',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'cli',
    flag: 'cli',
    label: 'cli',
    description: 'Create a developer cli environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 205,
      cdObjTypeName: 'cli',
      cdObjTypeGuid: 'f3d9bc12-3cd4-4ac0-a3b4-e6744a6495d6',
      modCraftController: 'Cli',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Cli',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'cd-cli',
    flag: 'cd-cli',
    label: 'cd-cli',
    description: 'Create a developer cd-cli environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 206,
      cdObjTypeName: 'cd-cli',
      cdObjTypeGuid: '9aab01ec-bce7-49c3-a2b5-3e697ac9b20e',
      modCraftController: 'CdCli',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'CdCli',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'pwa',
    flag: 'pwa',
    label: 'pwa',
    description: 'Create a developer pwa environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 207,
      cdObjTypeName: 'pwa',
      cdObjTypeGuid: '6e0b5a1a-08df-476b-8a1f-17d45017d96c',
      modCraftController: 'Pwa',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Pwa',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'desktop-pwa',
    flag: 'desktop-pwa',
    label: 'desktop-pwa',
    description: 'Create a developer desktop-pwa environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 208,
      cdObjTypeName: 'desktop-pwa',
      cdObjTypeGuid: 'c9bce40d-7a98-49ee-a875-3b476a982057',
      modCraftController: 'DesktopPwa',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'DesktopPwa',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'mobile',
    flag: 'mobile',
    label: 'mobile',
    description: 'Create a developer mobile environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 209,
      cdObjTypeName: 'mobile',
      cdObjTypeGuid: '0f6f3342-35dc-47f5-a7d7-3f456f9a83cd',
      modCraftController: 'Mobile',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Mobile',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'mobile-hybrid',
    flag: 'mobile-hybrid',
    label: 'mobile-hybrid',
    description: 'Create a developer mobile-hybrid environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 210,
      cdObjTypeName: 'mobile-hybrid',
      cdObjTypeGuid: 'b39bcd3f-1966-4c70-b594-5fd5b09cb8c2',
      modCraftController: 'MobileHybrid',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'MobileHybrid',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'mobile-native',
    flag: 'mobile-native',
    label: 'mobile-native',
    description: 'Create a developer mobile-native environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 211,
      cdObjTypeName: 'mobile-native',
      cdObjTypeGuid: 'ebfa4828-2e7e-4bde-a2d4-1455d038b59c',
      modCraftController: 'MobileNative',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'MobileNative',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'desktop',
    flag: 'desktop',
    label: 'desktop',
    description: 'Create a developer desktop environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 212,
      cdObjTypeName: 'desktop',
      cdObjTypeGuid: '9992f62b-b700-4d00-aab3-dcf236780f57',
      modCraftController: 'Desktop',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Desktop',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'iot',
    flag: 'iot',
    label: 'iot',
    description: 'Create a developer iot environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 213,
      cdObjTypeName: 'iot',
      cdObjTypeGuid: '726ea70f-86f5-4657-b75c-607f57dc7ae2',
      modCraftController: 'Iot',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Iot',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'game',
    flag: 'game',
    label: 'game',
    description: 'Create a developer game environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 214,
      cdObjTypeName: 'game',
      cdObjTypeGuid: '4d53c30b-2249-4c25-aef0-b444dbf26077',
      modCraftController: 'Game',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Game',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'embedded',
    flag: 'embedded',
    label: 'embedded',
    description: 'Create a developer embedded environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 215,
      cdObjTypeName: 'embedded',
      cdObjTypeGuid: '22c94ed7-4b2e-4b21-90cf-fba2c1d83699',
      modCraftController: 'Embedded',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Embedded',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'robotics',
    flag: 'robotics',
    label: 'robotics',
    description: 'Create a developer robotics environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 216,
      cdObjTypeName: 'robotics',
      cdObjTypeGuid: '6c1e7402-ea47-4dbe-8001-6f1505f46aa6',
      modCraftController: 'Robotics',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Robotics',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'plugin',
    flag: 'plugin',
    label: 'plugin',
    description: 'Create a developer plugin environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 217,
      cdObjTypeName: 'plugin',
      cdObjTypeGuid: '6c98fc1f-8137-4967-a6bb-c84d89175526',
      modCraftController: 'Plugin',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Plugin',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'microservice',
    flag: 'microservice',
    label: 'microservice',
    description: 'Create a developer microservice environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 218,
      cdObjTypeName: 'microservice',
      cdObjTypeGuid: '0c1e3f44-126c-4bb1-a1a3-95e9b6d700be',
      modCraftController: 'Microservice',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Microservice',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'sdn',
    flag: 'sdn',
    label: 'sdn',
    description: 'Create a developer sdn environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 219,
      cdObjTypeName: 'sdn',
      cdObjTypeGuid: '7d63ae7a-60bb-4bfa-82aa-1c8c14269a26',
      modCraftController: 'Sdn',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Sdn',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
  {
    name: 'cbo',
    flag: 'cbo',
    label: 'cbo',
    description: 'Create a developer cbo environment',
    action: 1,
    actionTarget: {
      cdObjTypeId: 220,
      cdObjTypeName: 'cbo',
      cdObjTypeGuid: '96cf624b-1bd5-4471-9ae2-1dc258e40992',
      modCraftController: 'Cbo',
    },
    requiredOptions: ['name', 'o-env'],
    targetName: 'cd-ai',
    targetType: 'cd-api',
    cdRequest: {
      ctx: 'app',
      m: 'app-craft',
      c: 'Cbo',
      a: 'create',
      dat: [Object],
      args: null,
    },
  },
];
